title: OmnySync Planner - Diploma
404_title: OmnySync Planner - 404
email: zhdanov.vdm@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is page for downloading script for diploma work of
  Vadim Zhdanov
show_downloads: true
github:
    zip_url: http://example.com
    tar_url: http://exmaple.com

# Build settings
theme: jekyll-theme-slate
plugins:
  - jekyll-feed
