name: OmnySync-CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  PROD:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Upload files to Google Drive
        uses: Jodebu/upload-to-drive@master
        with:
          target: ./OmnySync.Script
          credentials: ${{ secrets.GOOGLE_CRED }}
          folder: ${{ secrets.FOLDER_ID }}




